"""
Base Strategy Interface for NIRAJ Trading System

Abstract base class defining the interface for all trading strategies.
Provides common functionality, lifecycle management, and integration with
AI learning engine for continuous improvement.

All trading strategies must inherit from this class and implement the required methods.
"""

import abc
import uuid
import structlog
from datetime import datetime, time as datetime_time
from typing import Dict, Any, List, Optional, Protocol, TYPE_CHECKING
from dataclasses import dataclass, field
from enum import Enum

# Type checking imports
if TYPE_CHECKING:
    from ai.learning_engine import LearningEngine, AdaptationTrigger
else:
    try:
        from ai.learning_engine import LearningEngine, AdaptationTrigger
        HAS_LEARNING_ENGINE = True
    except ImportError:
        LearningEngine = None  # type: ignore
        AdaptationTrigger = None  # type: ignore
        HAS_LEARNING_ENGINE = False

from models.strategy import StrategyStatus
from models.strategy_signal import SignalType
from models.trade import Trade, TradeType
from models.portfolio import Portfolio
from models.market_data import MarketData

# Configure structured logging
logger = structlog.get_logger(__name__)


class StrategyType(str, Enum):
    """Types of trading strategies"""

    PREDATORY = "predatory"
    PSYCHOLOGICAL = "psychological"
    QUANTITATIVE = "quantitative"
    ARBITRAGE = "arbitrage"
    MOMENTUM = "momentum"
    MEAN_REVERSION = "mean_reversion"
    MACHINE_LEARNING = "machine_learning"


class StrategyPhase(str, Enum):
    """Strategy execution phases"""

    INITIALIZING = "initializing"
    ANALYZING = "analyzing"
    SIGNAL_GENERATION = "signal_generation"
    POSITION_SIZING = "position_sizing"
    RISK_CHECK = "risk_check"
    EXECUTION = "execution"
    MONITORING = "monitoring"
    ADAPTATION = "adaptation"
    CLEANUP = "cleanup"


class StrategyError(Exception):
    """Base exception for strategy errors"""

    def __init__(self, message: str, strategy_id: Optional[str] = None, error_code: Optional[str] = None):
        self.message = message
        self.strategy_id = strategy_id
        self.error_code = error_code
        super().__init__(self.message)


class SignalGenerationError(StrategyError):
    """Exception for signal generation failures"""

    pass


class RiskManagementError(StrategyError):
    """Exception for risk management failures"""

    pass


class ExecutionError(StrategyError):
    """Exception for trade execution failures"""

    pass


@dataclass
class StrategyConfig:
    """Configuration for trading strategies"""

    strategy_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    name: str = ""
    description: Optional[str] = None
    strategy_type: StrategyType = StrategyType.MACHINE_LEARNING

    # Risk parameters
    max_position_size: float = 0.1
    max_drawdown_limit: float = 0.05
    stop_loss_percentage: float = 0.02
    take_profit_percentage: float = 0.05

    # Trading parameters
    min_signal_strength: float = 0.6
    max_trades_per_day: int = 10
    trading_hours_start: str = "09:15"
    trading_hours_end: str = "15:30"

    # AI/ML parameters
    learning_enabled: bool = True
    adaptation_interval_minutes: int = 60
    model_update_threshold: float = 0.05

    # Market parameters
    supported_symbols: List[str] = field(default_factory=lambda: ["NIFTY", "BANKNIFTY"])
    min_volume_threshold: int = 1000

    # Custom parameters
    custom_params: Dict[str, Any] = field(default_factory=dict)


@dataclass
class MarketAnalysis:
    """Result of market analysis"""

    timestamp: datetime = field(default_factory=datetime.utcnow)
    symbol: str = ""
    analysis_type: str = ""

    # Technical indicators
    indicators: Dict[str, Any] = field(default_factory=dict)

    # AI analysis results
    ai_insights: Dict[str, Any] = field(default_factory=dict)

    # Market sentiment
    sentiment_score: float = 0.0  # -1 to 1

    # Risk metrics
    volatility: float = 0.0
    liquidity_score: float = 0.0

    # Metadata
    confidence_score: float = 0.0
    processing_time_ms: float = 0.0


@dataclass
class TradingSignal:
    """Trading signal generated by strategy"""

    signal_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    strategy_id: str = ""
    symbol: str = ""
    signal_type: SignalType = SignalType.BUY
    strength: float = 0.0  # 0-1 confidence score

    # Price levels
    entry_price: Optional[float] = None
    stop_loss_price: Optional[float] = None
    take_profit_price: Optional[float] = None

    # Position sizing
    position_size_percentage: float = 0.0  # % of portfolio
    quantity: Optional[int] = None

    # Timing
    timestamp: datetime = field(default_factory=datetime.utcnow)
    expiry_minutes: int = 60  # Signal expiry

    # Reasoning
    reasoning: str = ""
    supporting_data: Dict[str, Any] = field(default_factory=dict)

    # Risk metrics
    risk_reward_ratio: float = 0.0
    expected_return: float = 0.0
    max_drawdown_risk: float = 0.0


@dataclass
class StrategyPerformance:
    """Performance metrics for strategy"""

    strategy_id: str = ""
    total_trades: int = 0
    winning_trades: int = 0
    losing_trades: int = 0

    # Financial metrics
    total_return: float = 0.0
    annualized_return: float = 0.0
    sharpe_ratio: float = 0.0
    max_drawdown: float = 0.0

    # Risk metrics
    win_rate: float = 0.0
    avg_win: float = 0.0
    avg_loss: float = 0.0
    profit_factor: float = 0.0

    # AI metrics
    ai_accuracy: float = 0.0
    signal_quality: float = 0.0
    adaptation_count: int = 0

    # Time metrics
    active_days: int = 0
    last_updated: datetime = field(default_factory=datetime.utcnow)


class BaseStrategy(abc.ABC):
    """
    Abstract base class for all trading strategies in NIRAJ system.

    Provides common functionality, lifecycle management, and integration
    with AI learning engine for continuous strategy improvement.
    """

    def __init__(
        self,
        config: StrategyConfig,
        learning_engine: Optional["LearningEngine"] = None
    ) -> None:
        """Initialize the trading strategy"""
        self.config: StrategyConfig = config
        self.learning_engine: Optional["LearningEngine"] = learning_engine

        # Strategy state
        self.strategy_id: str = config.strategy_id
        self.status: StrategyStatus = StrategyStatus.INACTIVE
        self.current_phase: StrategyPhase = StrategyPhase.INITIALIZING

        # Performance tracking
        self.performance: StrategyPerformance = StrategyPerformance(strategy_id=self.strategy_id)

        # Active signals and positions
        self.active_signals: Dict[str, TradingSignal] = {}
        self.active_positions: Dict[str, Dict[str, Any]] = {}

        # Market data cache
        self.market_data_cache: Dict[str, MarketData] = {}
        self.last_analysis: Dict[str, MarketAnalysis] = {}

        # Learning state
        self.last_adaptation: datetime = datetime.utcnow()
        self.learning_sessions: List[str] = []

        # Error handling
        self.error_count: int = 0
        self.last_error: Optional[str] = None
        self.consecutive_failures: int = 0

        logger.info(
            "Strategy initialized",
            strategy_id=self.strategy_id,
            type=config.strategy_type.value,
            name=config.name,
        )

    @abc.abstractmethod
    async def initialize(self) -> bool:
        """
        Initialize the strategy with required resources and models.

        Returns:
            True if initialization successful, False otherwise

        Raises:
            StrategyError: If initialization fails
        """
        pass

    @abc.abstractmethod
    async def analyze_market(self, market_data: MarketData) -> MarketAnalysis:
        """
        Analyze market data and generate insights.

        Args:
            market_data: Current market data

        Returns:
            MarketAnalysis with technical and AI insights

        Raises:
            StrategyError: If analysis fails
        """
        pass

    @abc.abstractmethod
    async def generate_signals(self, analysis: MarketAnalysis) -> List[TradingSignal]:
        """
        Generate trading signals based on market analysis.

        Args:
            analysis: Market analysis results

        Returns:
            List of trading signals

        Raises:
            SignalGenerationError: If signal generation fails
        """
        pass

    @abc.abstractmethod
    async def calculate_position_size(
        self, signal: TradingSignal, portfolio: Portfolio
    ) -> float:
        """
        Calculate position size for a trading signal.

        Args:
            signal: Trading signal
            portfolio: Current portfolio state

        Returns:
            Position size as percentage of portfolio

        Raises:
            StrategyError: If position sizing fails
        """
        pass

    async def validate_signal(self, signal: TradingSignal) -> bool:
        """
        Validate a trading signal before execution.

        Args:
            signal: Signal to validate

        Returns:
            True if signal is valid for execution
        """
        try:
            # Check signal strength
            if signal.strength < self.config.min_signal_strength:
                logger.debug(
                    "Signal strength below threshold", signal_id=signal.signal_id
                )
                return False

            # Check risk parameters
            if signal.stop_loss_price is not None and signal.entry_price is not None:
                stop_loss_pct = (
                    abs(signal.stop_loss_price - signal.entry_price)
                    / signal.entry_price
                )
                if stop_loss_pct > self.config.stop_loss_percentage:
                    logger.debug("Stop loss exceeds limit", signal_id=signal.signal_id)
                    return False

            # Check position size limits
            if signal.position_size_percentage > self.config.max_position_size:
                logger.debug("Position size exceeds limit", signal_id=signal.signal_id)
                return False

            # Check trading hours
            current_time = datetime.utcnow()
            ist_time = current_time  # Simplified, should convert to IST

            trading_start: datetime_time = datetime.strptime(
                self.config.trading_hours_start, "%H:%M"
            ).time()
            trading_end: datetime_time = datetime.strptime(
                self.config.trading_hours_end, "%H:%M"
            ).time()
            current_time_only: datetime_time = ist_time.time()

            if not (trading_start <= current_time_only <= trading_end):
                logger.debug("Outside trading hours", signal_id=signal.signal_id)
                return False

            return True

        except Exception as e:
            logger.error(
                "Signal validation failed", signal_id=signal.signal_id, error=str(e)
            )
            return False

    async def execute_signal(
        self, signal: TradingSignal, portfolio: Portfolio
    ) -> Optional[Trade]:
        """
        Execute a validated trading signal.

        Args:
            signal: Validated trading signal
            portfolio: Current portfolio state

        Returns:
            Trade object if execution successful, None otherwise

        Raises:
            ExecutionError: If execution fails
        """
        try:
            self.current_phase = StrategyPhase.EXECUTION

            # Calculate position size
            position_size = await self.calculate_position_size(signal, portfolio)

            # Validate signal has required fields
            if signal.entry_price is None:
                raise ExecutionError("Signal missing entry price", self.strategy_id)

            # Create trade object
            trade = Trade(
                strategy_id=self.strategy_id,
                symbol=signal.symbol,
                trade_type=(
                    TradeType.BUY
                    if signal.signal_type == SignalType.BUY
                    else TradeType.SELL
                ),
                quantity=int(
                    position_size * portfolio.total_value / signal.entry_price
                ),
                price=signal.entry_price,
                stop_loss=signal.stop_loss_price,
                take_profit=signal.take_profit_price,
            )

            # Execute trade (placeholder - integrate with broker API)
            execution_result = await self._execute_trade(trade)

            if execution_result:
                # Update active positions
                self.active_positions[trade.trade_id] = {
                    "trade": trade,
                    "signal": signal,
                    "entry_time": datetime.utcnow(),
                }

                # Update performance
                self.performance.total_trades += 1

                logger.info(
                    "Signal executed successfully",
                    signal_id=signal.signal_id,
                    trade_id=trade.trade_id,
                    symbol=signal.symbol,
                )

                return trade
            else:
                logger.warning("Signal execution failed", signal_id=signal.signal_id)
                return None

        except Exception as e:
            self.error_count += 1
            self.last_error = str(e)
            logger.error(
                "Signal execution failed", signal_id=signal.signal_id, error=str(e)
            )
            raise ExecutionError(
                f"Failed to execute signal: {str(e)}", self.strategy_id
            )

    async def manage_risk(self, portfolio: Portfolio) -> List[str]:
        """
        Perform risk management checks and actions.

        Args:
            portfolio: Current portfolio state

        Returns:
            List of risk management actions taken

        Raises:
            RiskManagementError: If risk management fails
        """
        try:
            self.current_phase = StrategyPhase.RISK_CHECK
            actions_taken: List[str] = []

            # Check portfolio drawdown
            if portfolio.current_drawdown > self.config.max_drawdown_limit:
                actions_taken.append("portfolio_drawdown_exceeded")
                await self._emergency_stop("Portfolio drawdown limit exceeded")

            # Check individual position risks
            for position_id, position_data in self.active_positions.items():
                trade: Trade = position_data["trade"]
                current_price = await self._get_current_price(trade.symbol)

                if current_price is not None:
                    # Check stop loss
                    stop_loss_triggered = trade.stop_loss is not None and (
                        (
                            trade.trade_type == TradeType.BUY
                            and current_price <= trade.stop_loss
                        )
                        or (
                            trade.trade_type == TradeType.SELL
                            and current_price >= trade.stop_loss
                        )
                    )
                    if stop_loss_triggered:
                        await self._close_position(position_id, "stop_loss_hit")
                        actions_taken.append(f"stop_loss_triggered_{position_id}")

                    # Check take profit
                    take_profit_triggered = trade.take_profit is not None and (
                        (
                            trade.trade_type == TradeType.BUY
                            and current_price >= trade.take_profit
                        )
                        or (
                            trade.trade_type == TradeType.SELL
                            and current_price <= trade.take_profit
                        )
                    )
                    if take_profit_triggered:
                        await self._close_position(position_id, "take_profit_hit")
                        actions_taken.append(f"take_profit_triggered_{position_id}")

            # Check concentration limits
            symbol_exposure: Dict[str, float] = {}
            for position_data in self.active_positions.values():
                trade_obj: Trade = position_data["trade"]
                symbol = trade_obj.symbol
                exposure = trade_obj.quantity * trade_obj.price
                symbol_exposure[symbol] = symbol_exposure.get(symbol, 0.0) + exposure

            max_exposure_pct = 0.25  # Max 25% exposure per symbol
            for symbol, exposure in symbol_exposure.items():
                exposure_pct = exposure / portfolio.total_value
                if exposure_pct > max_exposure_pct:
                    actions_taken.append(f"concentration_limit_{symbol}")
                    # Reduce position (placeholder)

            return actions_taken

        except Exception as e:
            logger.error("Risk management failed", error=str(e))
            raise RiskManagementError(
                f"Risk management failed: {str(e)}", self.strategy_id
            )

    async def adapt_strategy(self, performance_feedback: Dict[str, Any]) -> bool:
        """
        Adapt strategy based on performance feedback using AI learning.

        Args:
            performance_feedback: Performance metrics and feedback

        Returns:
            True if adaptation successful, False otherwise
        """
        try:
            self.current_phase = StrategyPhase.ADAPTATION

            if (
                not self.learning_engine
                or not HAS_LEARNING_ENGINE
                or not self.config.learning_enabled
            ):
                logger.debug(
                    "Learning not enabled for strategy", strategy_id=self.strategy_id
                )
                return False

            # Check if adaptation is needed
            current_performance = performance_feedback.get("win_rate", 0.0)
            adaptation_threshold = self.config.model_update_threshold

            time_since_last_adaptation = (
                datetime.utcnow() - self.last_adaptation
            ).total_seconds() / 60

            if (
                current_performance < adaptation_threshold
                and time_since_last_adaptation
                >= self.config.adaptation_interval_minutes
            ):
                # Trigger adaptation - requires proper type guard
                if TYPE_CHECKING or (self.learning_engine is not None and AdaptationTrigger is not None):
                    session_id = await self.learning_engine.trigger_adaptation(
                        model_id=self.strategy_id,
                        trigger=AdaptationTrigger.PERFORMANCE_DEGRADATION,
                        trigger_data={
                            "current_performance": current_performance,
                            "threshold": adaptation_threshold,
                            "strategy_type": self.config.strategy_type.value,
                        },
                    )

                    if session_id:
                        self.learning_sessions.append(session_id)
                        self.last_adaptation = datetime.utcnow()
                        self.performance.adaptation_count += 1

                        logger.info(
                            "Strategy adaptation triggered",
                            strategy_id=self.strategy_id,
                            session_id=session_id,
                        )

                        return True

            return False

        except Exception as e:
            logger.error("Strategy adaptation failed", error=str(e))
            return False

    async def update_performance(self, trade_result: Dict[str, Any]) -> None:
        """
        Update strategy performance metrics.

        Args:
            trade_result: Result of a completed trade
        """
        try:
            pnl = trade_result.get("pnl", 0.0)
            is_win = pnl > 0

            if is_win:
                self.performance.winning_trades += 1
                self.performance.avg_win = (
                    (self.performance.avg_win * (self.performance.winning_trades - 1))
                    + pnl
                ) / self.performance.winning_trades
            else:
                self.performance.losing_trades += 1
                self.performance.avg_loss = (
                    (self.performance.avg_loss * (self.performance.losing_trades - 1))
                    + abs(pnl)
                ) / self.performance.losing_trades

            # Update ratios
            if self.performance.total_trades > 0:
                self.performance.win_rate = (
                    self.performance.winning_trades / self.performance.total_trades
                )

            if self.performance.avg_loss > 0 and self.performance.total_trades > 0:
                self.performance.profit_factor = (
                    self.performance.avg_win
                    * self.performance.win_rate
                    / (abs(self.performance.avg_loss) * (1 - self.performance.win_rate))
                )

            self.performance.total_return += pnl
            self.performance.last_updated = datetime.utcnow()

        except Exception as e:
            logger.error("Performance update failed", error=str(e))

    async def cleanup(self) -> None:
        """Cleanup strategy resources"""
        try:
            self.current_phase = StrategyPhase.CLEANUP

            # Close all active positions
            for position_id in list(self.active_positions.keys()):
                await self._close_position(position_id, "strategy_shutdown")

            # Clear caches
            self.active_signals.clear()
            self.active_positions.clear()
            self.market_data_cache.clear()
            self.last_analysis.clear()

            # Update status
            self.status = StrategyStatus.INACTIVE

            logger.info("Strategy cleanup completed", strategy_id=self.strategy_id)

        except Exception as e:
            logger.error("Strategy cleanup failed", error=str(e))

    async def health_check(self) -> Dict[str, Any]:
        """
        Perform health check on the strategy.

        Returns:
            Health status dictionary
        """
        try:
            health = {
                "strategy_id": self.strategy_id,
                "status": "healthy",
                "phase": self.current_phase.value,
                "active_signals": len(self.active_signals),
                "active_positions": len(self.active_positions),
                "error_count": self.error_count,
                "last_error": self.last_error,
                "performance": {
                    "total_trades": self.performance.total_trades,
                    "win_rate": self.performance.win_rate,
                    "total_return": self.performance.total_return,
                },
            }

            # Check for issues
            if self.error_count > 10:
                health["status"] = "degraded"
                health["issues"] = ["high_error_count"]

            if self.consecutive_failures > 3:
                health["status"] = "unhealthy"
                health["issues"] = ["consecutive_failures"]

            if self.performance.win_rate < 0.3 and self.performance.total_trades > 50:
                health["status"] = "degraded"
                health["issues"] = ["poor_performance"]

            return health

        except Exception as e:
            return {
                "strategy_id": self.strategy_id,
                "status": "unhealthy",
                "error": str(e),
            }

    # Placeholder methods to be implemented by subclasses or integrated with APIs

    async def _execute_trade(self, trade: Trade) -> bool:
        """Execute a trade (placeholder for broker API integration)"""
        # Placeholder - integrate with Angel One, Dhan, etc.
        logger.info("Trade execution placeholder", trade_id=trade.trade_id)
        return True

    async def _close_position(self, position_id: str, reason: str) -> None:
        """Close an active position"""
        if position_id in self.active_positions:
            logger.info("Position closed", position_id=position_id, reason=reason)
            del self.active_positions[position_id]

    async def _get_current_price(self, symbol: str) -> Optional[float]:
        """Get current price for symbol"""
        # Placeholder - integrate with market data API
        return 100.0  # Dummy price

    async def _emergency_stop(self, reason: str) -> None:
        """Emergency stop for strategy"""
        logger.critical("Emergency stop triggered", strategy_id=self.strategy_id, reason=reason)
        self.status = StrategyStatus.INACTIVE
        await self.cleanup()

    # Strategy lifecycle methods

    async def start(self) -> bool:
        """Start the strategy"""
        try:
            if self.status != StrategyStatus.INACTIVE:
                return False

            success = await self.initialize()
            if success:
                self.status = StrategyStatus.ACTIVE
                logger.info("Strategy started", strategy_id=self.strategy_id)
                return True
            else:
                logger.error(
                    "Strategy initialization failed", strategy_id=self.strategy_id
                )
                return False

        except Exception as e:
            logger.error("Failed to start strategy", error=str(e))
            return False

    async def stop(self):
        """Stop the strategy"""
        try:
            await self.cleanup()
            logger.info("Strategy stopped", strategy_id=self.strategy_id)

        except Exception as e:
            logger.error("Failed to stop strategy", error=str(e))

    async def pause(self):
        """Pause the strategy"""
        self.status = StrategyStatus.PAUSED
        logger.info("Strategy paused", strategy_id=self.strategy_id)

    async def resume(self):
        """Resume the strategy"""
        if self.status == StrategyStatus.PAUSED:
            self.status = StrategyStatus.ACTIVE
            logger.info("Strategy resumed", strategy_id=self.strategy_id)

    # Utility methods

    def get_config_value(self, key: str, default: Any = None) -> Any:
        """Get configuration value"""
        return self.config.custom_params.get(key, default)

    def set_config_value(self, key: str, value: Any) -> None:
        """Set configuration value"""
        self.config.custom_params[key] = value

    def log_strategy_event(self, event: str, data: Optional[Dict[str, Any]] = None) -> None:
        """Log strategy-specific event"""
        logger.info(
            "Strategy event", strategy_id=self.strategy_id, event=event, data=data or {}
        )
